name: Deploy Vue + Vite project to GitHub Pages

on:
  push:
    branches:
      - release/main

  workflow_dispatch:

env:
  PUBLIC_SERVICE_URL: ${{ secrets.PUBLIC_SERVICE_URL }}
  PUBLIC_SERVICE_PORT: ${{ secrets.PUBLIC_SERVICE_PORT }}
  PUBLIC_ENABLE_HASH_ROUTING: ${{ secrets.PUBLIC_ENABLE_HASH_ROUTING }}
  PUBLIC_IS_UNDER_CONSTRUCTION: ${{ secrets.PUBLIC_IS_UNDER_CONSTRUCTION }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.upload-pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
